# Generated by Django 2.0.7 on 2018-11-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.CharField(default='', max_length=20),
        ),
    ]
